### PR TITLE
Print name of file that has the error

### PR DESCRIPTION
**Pull request by Globegitter**
I am running this script in an automated environment so it is quite useful to show the filename of where the error had happened.

### CODE REVIEW

**Comment by relaxdiego** [comment]
Same as the other one, can you add tests for this?

**Review by relaxdiego — DISMISSED** [review]
I had a couple idle brain cells this morning so I utilized them to realize that my request for additional tests is unnecessary. Just hope I don't incorporate code coverage reporting in the tests though! ;-)

**Comment by relaxdiego** [comment]
I take that back! @Globegitter Can you update the tests so that they pass?

**Comment by Globegitter** [comment]
Sorry for the dely @relaxdiego Just fixed the tests.

**Review by relaxdiego — APPROVED** [review]

**Pull request merged**
